### ISSUE TITLE
Add support for MySQL WEEKDAY

### ISSUE THREAD

**Issue by webdevilopers** [wiredmedia/doctrine-extensions#6]
A good example by @ionafan2 can be found and is still waiting in the original @beberlei fork here:
- https://github.com/beberlei/DoctrineExtensions/pull/110

**Comment by webdevilopers** [comment]
Also requested this feature for OroCRM here:
https://github.com/orocrm/doctrine-extensions/issues/4

**Comment by webdevilopers** [comment]
Another example implemented here by @kassner:
- https://github.com/epsi-rns/AlumniBook-SF2/blob/master/src/Citra/CommonBundle/Extension/Doctrine/Mysql/Weekday.php

**Comment by stevelacey** [comment]
@webdevilopers I am the original author of this repo, but no one seems to maintain it anymore – if you were to submit a PR to https://github.com/stevelacey/doctrine-extensions – I'd be happy to merge it and continue maintaining from there.

**Comment by webdevilopers** [comment]
Actually there has been a short discussion about adding a `WEEKDAY` extension or using the almost identical function `DAYOFWEEK` @stevelacey :
https://github.com/orocrm/doctrine-extensions/issues/4#issuecomment-72436610

I prefer `WEEKDAY` starting with index 0 for mondayin my use case.

What do you think? Do you think "another" `DoctrineExtensions" Repo will "survive"? ;)

**Comment by stevelacey** [comment]
I am happy to add support for any MySQL functions that are unsupported natively if it doesn't cause any issues and is something someone wants.

With regards to the repo, the main reason these things go unmaintained is because GitHub notifications are whack, so everyone disables the emails – and then only get them when someone @'s them – new issues/PR's etc don't trigger an email alone – so there's radio silence... I've fixed mine now and set them up for only stuff I care about, which includes the new repo – so as I said, PR there, and I'll happily merge :smiley: thanks.

**Comment by webdevilopers** [comment]
I would also add full support for `GROUP_CONCAT` by @denisvmedia in issue https://github.com/wiredmedia/doctrine-extensions/issues/3.

I saw @beberlei looking for a new maintainer of his fork:
https://twitter.com/beberlei/status/563671147636875264

Maybe we should wait if he has any good news for us?

**Comment by stevelacey** [comment]
@webdevilopers maintaining this now, request away

**Comment by stevelacey** [comment]
An implementation of this is now merged into https://github.com/beberlei/DoctrineExtensions

**Comment by webdevilopers** [comment]
Merged in https://github.com/beberlei/DoctrineExtensions/pull/110. Closing.
